name: metagit-ai
description: Metagit is situational awareness for developers made easy. Metagit can
  make multi-repo projects feel more like a monorepo and provide information on the
  software stacks within.
url: https://metagit.ai
kind: cli
documentation:
- docs/cli_reference.md
- docs/development.md
- docs/docker_multitenant.md
- docs/multi_tenancy.md
- docs/per_tenant_configuration.md
- docs/repository_detection.md
- docs/terminology.md
license:
  kind: MIT
  file: LICENSE
maintainers:
- name: Zachary Loeber
  email: zloeber@gmail.com
  role: Contributor
- name: Zachary Loeber
  email: zloeber@users.noreply.github.com
  role: Contributor
branch_strategy: none
taskers:
- kind: Taskfile
artifacts:
- type: python_package
  definition: pyproject.toml
  location: dist/
  version_strategy: semver
- type: docker
  definition: Dockerfile.api
  location: metagit-api
  version_strategy: semver
cicd:
  platform: GitHub
  pipelines:
  - name: Lint and Test
    ref: .github/workflows/lint-and-test.yaml
  - name: Docs
    ref: .github/workflows/docs.yaml
  - name: PR and Push
    ref: .github/workflows/pr-and-push.yaml
  - name: Publish CLI
    ref: .github/workflows/publish-cli.yaml
observability:
  logging_provider: elk
  monitoring_providers:
  - grafana
  dashboards:
  - name: OpenSearch Dashboards
    tool: OpenSearch
    url: http://localhost:5601
paths:
- name: metagit
  description: The main project path
  kind: application
  path: ./metagit
  language: python
  language_version: '3.12'
  package_manager: uv
  frameworks:
  - CrewAI
  - Click
dependencies:
- name: dragonflydb_latest
  description: DragonflyDB is a modern, in-memory database that is designed to be
    fast, scalable, and easy to use.
  kind: docker_image
  ref: ./docker-compose.yml
  url: https://github.com/dragonflydb/dragonfly
- name: ubuntu_latest
  description: Ubuntu is a Linux distribution based on Debian and composed mostly
    of free and open-source software.
  kind: docker_image
  ref: ./.github/workflows/lint-and-test.yaml
workspace:
  projects:
  - name: default
    repos:
    - name: metagit_detect
      description: The main project path
      kind: application
      path: ./metagit_detect
      branches: []
      sync: false
      language: python
      language_version: '3.12'
      package_manager: uv
      frameworks:
      - CrewAI
      - Click
    - name: dragonflydb_latest
      description: DragonflyDB is a modern, in-memory database that is designed to
        be fast, scalable, and easy to use.
      kind: docker_image
      ref: ./docker-compose.yml
      url: https://github.com/dragonflydb/dragonfly
      sync: false
    - name: ubuntu_latest
      description: Ubuntu is a Linux distribution based on Debian and composed mostly
        of free and open-source software.
      kind: docker_image
      path: ./.gitlab/workflows/metagit.yml
      sync: false
  - name: project2
    repos:
    - name: some_other_project
      description: Some other project
      kind: application
      path: ./some_other_project
      branches: []
      url: https://github.com/metagit-io/some_other_project
      sync: true
