name: metagit-detect
description: unknown
url: git@github.com:metagit-ai/metagit-detect.git
kind: umbrella
branch_strategy: unknown
artifacts: []
paths: []
dependencies: []
workspace:
  projects:
  - name: default
    repos: []
