artifacts:
- definition: pyproject.toml
  location: dist/
  type: python_package
  version_strategy: semver
- definition: Dockerfile.api
  location: metagit-api
  type: docker
  version_strategy: semver
branch_strategy: none
cicd:
  pipelines:
  - name: Lint and Test
    ref: .github/workflows/lint-and-test.yaml
  - name: Docs
    ref: .github/workflows/docs.yaml
  - name: PR and Push
    ref: .github/workflows/pr-and-push.yaml
  - name: Publish CLI
    ref: .github/workflows/publish-cli.yaml
  platform: GitHub
dependencies:
- description: DragonflyDB is a modern, in-memory database that is designed to be
    fast, scalable, and easy to use.
  kind: docker_image
  name: dragonflydb_latest
  ref: ./docker-compose.yml
  url: https://github.com/dragonflydb/dragonfly
- description: Ubuntu is a Linux distribution based on Debian and composed mostly
    of free and open-source software.
  kind: docker_image
  name: ubuntu_latest
  ref: ./.github/workflows/lint-and-test.yaml
description: Metagit is situational awareness for developers made easy. Metagit can
  make multi-repo projects feel more like a monorepo and provide information on the
  software stacks within. <details> <summary>Tabl
kind: cli
license:
  file: LICENSE
  kind: MIT
maintainers:
- email: zloeber@gmail.com
  name: Zachary Loeber
  role: Contributor
- email: zloeber@users.noreply.github.com
  name: Zachary Loeber
  role: Contributor
name: metagit-detect
observability:
  dashboards:
  - name: OpenSearch Dashboards
    tool: OpenSearch
    url: http://localhost:5601/
  logging_provider: elk
  monitoring_providers:
  - grafana
paths:
- description: The main project path
  frameworks:
  - CrewAI
  - Click
  kind: application
  language: python
  language_version: '3.12'
  name: metagit
  package_manager: uv
  path: ./metagit
taskers:
- kind: Taskfile
workspace:
  projects:
  - name: default
    repos:
    - branches: []
      description: The main project path
      frameworks:
      - CrewAI
      - Click
      kind: application
      language: python
      language_version: '3.12'
      name: metagit_detect
      package_manager: uv
      path: ./metagit_detect
      sync: false
    - description: DragonflyDB is a modern, in-memory database that is designed to
        be fast, scalable, and easy to use.
      kind: docker_image
      name: dragonflydb_latest
      ref: ./docker-compose.yml
      sync: false
      url: https://github.com/dragonflydb/dragonfly
    - description: Ubuntu is a Linux distribution based on Debian and composed mostly
        of free and open-source software.
      kind: docker_image
      name: ubuntu_latest
      path: ./.gitlab/workflows/metagit.yml
      sync: false
    - name: test
  - name: project2
    repos:
    - branches: []
      description: Some other project
      kind: application
      name: some_other_project
      path: ./some_other_project
      sync: true
      url: https://github.com/metagit-io/some_other_project
