name: metagit-detect
description: Metagit is situational awareness for developers made easy. Metagit can
  make multi-repo projects feel more like a monorepo and provide information on the
  software stacks within. <details> <summary>Tabl
kind: cli
license:
  kind: MIT
  file: LICENSE
maintainers:
- name: Zachary Loeber
  email: zloeber@gmail.com
  role: Contributor
- name: Zachary Loeber
  email: zloeber@users.noreply.github.com
  role: Contributor
branch_strategy: none
taskers:
- kind: Taskfile
cicd:
  platform: GitHub
  pipelines:
  - name: default
    ref: .github/workflows
workspace:
  projects:
  - name: default
    repos:
    - name: metagit_detect
      description: The main project path
      kind: application
      path: ./metagit_detect
      branches: []
      sync: false
      language: python
      language_version: '3.12'
      package_manager: uv
      frameworks:
      - CrewAI
      - Click
    - name: dragonflydb_latest
      description: DragonflyDB is a modern, in-memory database that is designed to
        be fast, scalable, and easy to use.
      kind: docker_image
      ref: ./docker-compose.yml
      url: https://github.com/dragonflydb/dragonfly
      sync: false
    - name: ubuntu_latest
      description: Ubuntu is a Linux distribution based on Debian and composed mostly
        of free and open-source software.
      kind: docker_image
      path: ./.gitlab/workflows/metagit.yml
      sync: false
  - name: project2
    repos:
    - name: some_other_project
      description: Some other project
      kind: application
      path: ./some_other_project
      branches: []
      url: https://github.com/metagit-io/some_other_project
      sync: true
