config:
  version: "0.1.0"
  description: "Configuration for metagit CLI"

  global:
    debug: false
    verbose: false
    strict: false
    override: ""
    # Reserved for future use
    metagit_api_url: ""
    # Reserved for future use
    metagit_api_version: ""
    # Reserved for future use
    metagit_api_key: ""
    # Reserved for future use
    cicd_file_data: data/cicd-files.json
    file_type_data: data/file-types.json
    package_manager_data: data/package-managers.json

  llm:
    provider: "openrouter"
    provider_model: "gpt-4o-mini"
    embedder: "ollama"
    embedder_model: "nomic-embed-text"
    api_key: ""

  workspace:
    # Default workspace path, should be added to .gitignore
    path: ./.metagit
    default: default
    auto_sync: false
    sync_on_start: false

  profiles:
    # Profiles are used to define multiple configurations for different organizations
    profile_config_path: ~/.config/metagit/profiles
    default_profile: "default"
    boundaries:
      # These are the platforms that are supported by the workspace.
      # Defined values are considered internal to the workspace.
      - name: github
        values: []
      - name: jfrog
        values: []
      - name: gitlab
        values: []
      - name: bitbucket
        values: []
      - name: azure_devops
        values: []
      - name: dockerhub
        values: []
      - name: domain
        values:
          - localhost
          - "127.0.0.1"
          - "0.0.0.0"
          - 192.168.*
          - 10.0.*
          - 172.16.*

# These are the equivalent of a tenant in a multi-tenant application
# default boundaries are inherited from the global boundaries
# profiles:
#   default:
#     name: "Personal"
#     boundaries:
#       - name: github
#         values: []
#       - name: jfrog
#         values: []
#       - name: gitlab
#         values: []

