[project]
name = "metagit-detect"
version = "0.1.0"
description = "MetaGit project detection agent"
requires-python = ">=3.12"
dependencies = [
    "logging>=0.4.9.6",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "requests>=2.32.3",
    "click>=8.1.7",
    "dotenv>=0.9.9",
    "gitpython>=3.1.44",
    "rich>=14.0.0",
    "pyyaml>=6.0.2",
    "crewai[tools]<=0.121.0",
    "pygithub>=2.6.1",
    "jsonschema>=4.24.0",
    "python-dotenv>=1.1.0",
    "rapidfuzz>=3.13.0",
    "prompt-toolkit>=3.0.51",
]

[lint]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293', 'E501']
exclude = ["app/**", "tools/**", ".venv"]

[dependency-groups]
dev = [
    "hatch>=1.13.0",
    "ruff>=0.11.11",
]
