#!/usr/bin/env python
"""Isolated HTTP client for the EverRoom NxCore Gateway."""

from __future__ import annotations

from typing import Any, Optional, Protocol
from urllib.parse import quote, urlencode, urljoin, urlparse

import requests

from metagit.core.integrations.everroom.errors import (
    EverRoomAuthError,
    EverRoomInvalidResponseError,
    EverRoomNotFoundError,
    EverRoomUnavailableError,
)
from metagit.core.integrations.everroom.models import (
    EverRoomCreateResult,
    EverRoomDecision,
    EverRoomDocumentRef,
    EverRoomHealth,
    EverRoomKnowledgeItem,
    EverRoomOverview,
    EverRoomRoom,
    EverRoomRoomContext,
    EverRoomSource,
)

_DEFAULT_TIMEOUT = 8.0
_HEALTH_PATHS = ("/v1/health/live", "/v1/health/ready")
_GENERATED_TITLE = "Campaign Context (generated by MetaGit)"


class EverRoomClient(Protocol):
    """Narrow Gateway operations needed by campaign context assembly."""

    def health(self) -> EverRoomHealth: ...

    def resolve_room(self, room_id: str) -> EverRoomRoom: ...

    def create_room(self, *, title: str, description: str) -> EverRoomCreateResult: ...

    def get_room_overview(self, room_id: str) -> EverRoomOverview: ...

    def get_room_context(self, room_id: str) -> EverRoomRoomContext: ...

    def list_room_sources(self, room_id: str) -> list[EverRoomSource]: ...

    def list_room_documents(self, room_id: str) -> list[EverRoomDocumentRef]: ...

    def list_room_decisions(self, room_id: str, *, limit: int = 20) -> list[EverRoomDecision]: ...

    def list_room_knowledge(self, room_id: str) -> list[EverRoomKnowledgeItem]: ...

    def upsert_generated_document(
        self,
        *,
        room_id: str,
        document_id: str,
        title: str,
        markdown: str,
    ) -> EverRoomDocumentRef: ...


class EverRoomHttpClient:
    """Loopback Gateway client. Tokens never appear in raised messages."""

    def __init__(
        self,
        *,
        endpoint: str,
        token: str = "",
        timeout_seconds: float = _DEFAULT_TIMEOUT,
        session: Optional[requests.Session] = None,
    ) -> None:
        self._endpoint = _normalize_endpoint(endpoint)
        self._token = token or ""
        self._timeout = timeout_seconds
        self._session = session or requests.Session()

    @property
    def endpoint(self) -> str:
        return self._endpoint

    def health(self) -> EverRoomHealth:
        """Public liveness, then readiness. Auth is not required."""
        live = self._request("GET", "/v1/health/live", authenticate=False)
        payload = _require_mapping(live)
        ready = self._request("GET", "/v1/health/ready", authenticate=False)
        _require_mapping(ready)
        return EverRoomHealth.model_validate(payload)

    def resolve_room(self, room_id: str) -> EverRoomRoom:
        snapshot = self._request("GET", "/v1/context-rooms", authenticate=True)
        room = _find_room(snapshot, room_id)
        if room is not None:
            return room
        knowledge = self._request("GET", "/v1/knowledge/rooms", authenticate=True)
        for item in _items(knowledge):
            candidate = _coerce_room(item)
            if candidate is not None and candidate.id == room_id:
                return candidate
        raise EverRoomNotFoundError(f"EverRoom Room not found: {room_id}")

    def create_room(self, *, title: str, description: str) -> EverRoomCreateResult:
        payload = self._request(
            "POST",
            "/v1/context-rooms",
            authenticate=True,
            json_body={"title": title, "description": description},
        )
        mapping = _require_mapping(payload)
        if "room" in mapping:
            return EverRoomCreateResult.model_validate(mapping)
        room = _coerce_room(mapping)
        if room is None:
            raise EverRoomInvalidResponseError("EverRoom create-room response was missing a room object")
        return EverRoomCreateResult(room=room, created=True)

    def get_room_overview(self, room_id: str) -> EverRoomOverview:
        payload = self._request(
            "GET",
            f"/v1/context-rooms/{quote(room_id, safe='')}/overview",
            authenticate=True,
        )
        mapping = _require_mapping(payload)
        return EverRoomOverview(roomId=room_id, payload=mapping)

    def get_room_context(self, room_id: str) -> EverRoomRoomContext:
        payload = self._request(
            "GET",
            f"/v1/knowledge/rooms/{quote(room_id, safe='')}/context",
            authenticate=True,
        )
        return EverRoomRoomContext.model_validate(_require_mapping(payload))

    def list_room_sources(self, room_id: str) -> list[EverRoomSource]:
        payload = self._request(
            "GET",
            f"/v1/knowledge/rooms/{quote(room_id, safe='')}/files",
            authenticate=True,
        )
        sources: list[EverRoomSource] = []
        for item in _items(payload):
            if not isinstance(item, dict) or not item.get("id"):
                continue
            source = EverRoomSource.model_validate(item)
            source.identity_hints = [
                hint for hint in (source.original_name, source.title, source.source_id, source.id) if hint
            ]
            sources.append(source)
        return sources

    def list_room_documents(self, room_id: str) -> list[EverRoomDocumentRef]:
        query = urlencode({"roomId": room_id, "trashed": "false"})
        payload = self._request("GET", f"/v1/documents?{query}", authenticate=True)
        documents: list[EverRoomDocumentRef] = []
        for item in _document_rows(payload):
            if not isinstance(item, dict) or not item.get("id"):
                continue
            document = EverRoomDocumentRef.model_validate(item)
            title = document.title or ""
            document.generated = _GENERATED_TITLE.lower() in title.lower() or str(document.id).startswith(
                "metagit-campaign-",
            )
            documents.append(document)
        return documents

    def list_room_decisions(self, room_id: str, *, limit: int = 20) -> list[EverRoomDecision]:
        query = urlencode({"limit": max(1, min(limit, 100))})
        payload = self._request("GET", f"/v1/knowledge/decisions?{query}", authenticate=True)
        decisions: list[EverRoomDecision] = []
        for item in _items(payload):
            if not isinstance(item, dict):
                continue
            decision = EverRoomDecision.model_validate(item)
            if decision.room_id and decision.room_id != room_id:
                continue
            if not decision.decision_id and not decision.title:
                continue
            decisions.append(decision)
        return decisions[:limit]

    def list_room_knowledge(self, room_id: str) -> list[EverRoomKnowledgeItem]:
        items: list[EverRoomKnowledgeItem] = []
        wiki = self._request(
            "GET",
            f"/v1/knowledge/rooms/{quote(room_id, safe='')}/wiki/pages",
            authenticate=True,
        )
        wiki_mapping = wiki if isinstance(wiki, dict) else {}
        for item in _items(wiki_mapping.get("items", wiki)):
            if not isinstance(item, dict):
                continue
            page_id = str(item.get("id") or item.get("path") or "")
            if not page_id:
                continue
            items.append(
                EverRoomKnowledgeItem(
                    id=page_id,
                    title=str(item.get("title") or page_id),
                    kind="wiki",
                    path=item.get("path"),
                ),
            )
        materials = self._request(
            "GET",
            f"/v1/knowledge/rooms/{quote(room_id, safe='')}/materials",
            authenticate=True,
        )
        for item in _items(materials):
            if not isinstance(item, dict):
                continue
            material_id = str(item.get("documentId") or item.get("id") or "")
            if not material_id:
                continue
            items.append(
                EverRoomKnowledgeItem.model_validate(
                    {
                        "id": material_id,
                        "title": item.get("title") or material_id,
                        "kind": "material",
                        "version": item.get("version"),
                        "updatedAt": item.get("updatedAt"),
                    },
                ),
            )
        return items

    def upsert_generated_document(
        self,
        *,
        room_id: str,
        document_id: str,
        title: str,
        markdown: str,
    ) -> EverRoomDocumentRef:
        content = markdown_to_tiptap(markdown)
        existing = {item.id: item for item in self.list_room_documents(room_id)}
        current = existing.get(document_id)
        if current is None:
            for item in existing.values():
                if item.generated:
                    current = item
                    break
        if current is None:
            payload = self._request(
                "POST",
                "/v1/documents/import",
                authenticate=True,
                json_body={
                    "id": document_id,
                    "roomId": room_id,
                    "title": title[:120],
                    "contentJson": content,
                },
            )
            return EverRoomDocumentRef.model_validate(_require_mapping(payload))
        payload = self._request(
            "PUT",
            f"/v1/documents/{quote(current.id, safe='')}",
            authenticate=True,
            json_body={
                "baseVersion": current.version,
                "title": title[:120],
                "contentJson": content,
            },
        )
        return EverRoomDocumentRef.model_validate(_require_mapping(payload))

    def _request(
        self,
        method: str,
        path: str,
        *,
        authenticate: bool,
        json_body: Optional[dict[str, Any]] = None,
    ) -> Any:
        url = urljoin(self._endpoint + "/", path.lstrip("/"))
        headers = {"Accept": "application/json"}
        if authenticate:
            if not self._token:
                raise EverRoomAuthError(
                    "EverRoom authentication failed: set METAGIT_EVERROOM_TOKEN "
                    "(do not store the token in campaign YAML or Git).",
                )
            headers["Authorization"] = f"Bearer {self._token}"
        try:
            response = self._session.request(
                method,
                url,
                headers=headers,
                json=json_body,
                timeout=self._timeout,
            )
        except requests.Timeout as exc:
            raise EverRoomUnavailableError("EverRoom Gateway timed out") from exc
        except requests.ConnectionError as exc:
            raise EverRoomUnavailableError("EverRoom Gateway is unavailable (connection refused)") from exc
        except requests.RequestException as exc:
            raise EverRoomUnavailableError("EverRoom Gateway is unavailable") from exc
        return self._parse_response(response, path=path)

    def _parse_response(self, response: requests.Response, *, path: str) -> Any:
        status = response.status_code
        if status in {401, 403}:
            raise EverRoomAuthError(
                "EverRoom authentication failed: check METAGIT_EVERROOM_TOKEN "
                "and that the Gateway bearer token is current.",
            )
        if status == 404:
            raise EverRoomNotFoundError(f"EverRoom resource not found: {path}")
        if status == 503 and path in _HEALTH_PATHS:
            raise EverRoomUnavailableError("EverRoom Gateway is not ready")
        if status >= 500:
            raise EverRoomUnavailableError(f"EverRoom Gateway returned HTTP {status}")
        if status >= 400:
            raise EverRoomInvalidResponseError(f"EverRoom Gateway rejected the request (HTTP {status})")
        if not response.content:
            return {}
        try:
            return response.json()
        except ValueError as exc:
            raise EverRoomInvalidResponseError("EverRoom Gateway returned a malformed JSON body") from exc


def markdown_to_tiptap(markdown: str) -> dict[str, Any]:
    """Convert generated markdown into a minimal Tiptap JSON document."""
    content: list[dict[str, Any]] = []
    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue
        if line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            level = min(max(hashes, 1), 3)
            text = line[hashes:].strip() or line
            content.append(
                {
                    "type": "heading",
                    "attrs": {"level": level},
                    "content": [{"type": "text", "text": text}],
                },
            )
            continue
        content.append({"type": "paragraph", "content": [{"type": "text", "text": line}]})
    if not content:
        content.append({"type": "paragraph"})
    return {"type": "doc", "content": content}


def _normalize_endpoint(endpoint: str) -> str:
    text = (endpoint or "").strip().rstrip("/")
    if not text:
        raise EverRoomUnavailableError("EverRoom endpoint is missing")
    parsed = urlparse(text)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise EverRoomUnavailableError("EverRoom endpoint must be an http(s) URL")
    return text


def _require_mapping(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict):
        raise EverRoomInvalidResponseError("EverRoom Gateway returned a non-object JSON body")
    return payload


def _items(payload: Any) -> list[Any]:
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for key in ("items", "rooms", "documents"):
            value = payload.get(key)
            if isinstance(value, list):
                return value
    return []


def _document_rows(payload: Any) -> list[Any]:
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for key in ("items", "documents"):
            value = payload.get(key)
            if isinstance(value, list):
                return value
        if payload.get("id"):
            return [payload]
    return []


def _find_room(payload: Any, room_id: str) -> Optional[EverRoomRoom]:
    mapping = payload if isinstance(payload, dict) else {}
    rooms = mapping.get("rooms") if isinstance(mapping.get("rooms"), list) else _items(payload)
    for item in rooms:
        room = _coerce_room(item)
        if room is not None and room.id == room_id:
            return room
    return None


def _coerce_room(item: Any) -> Optional[EverRoomRoom]:
    if not isinstance(item, dict):
        return None
    room_id = item.get("id")
    if not isinstance(room_id, str) or not room_id:
        nested = item.get("room")
        if isinstance(nested, dict):
            return _coerce_room(nested)
        return None
    return EverRoomRoom.model_validate(item)
