version: "3"
silent: true

tasks:
  show:
    desc: Show python variables for this task
    cmds:
      - |
        echo "GIT_LATEST_TAG: {{.GIT_LATEST_TAG}}"
        echo "VERSION: {{.VERSION}}"

  test:detect:
    desc: Run the api tests
    cmds:
      - |
        curl -X POST "http://localhost:8000/detect" \
          -H "Content-Type: application/json" \
          -d '{
            "repository_url": "https://github.com/zloeber/mag-branch",
            "priority": "normal"
          }'

  dev:
    desc: Run the api in dev mode
    env:
      OPENSEARCH_HOST: localhost
      OPENSEARCH_PORT: 9200
      OPENSEARCH_INDEX: metagit-records
      OPENSEARCH_USE_SSL: false
      OPENSEARCH_VERIFY_CERTS: false
      API_HOST: 0.0.0.0
      API_PORT: 8000
      API_DEBUG: true
      MAX_CONCURRENT_JOBS: 5
    cmds:
      - |
        docker compose -f docker-compose.dev.yml up -d
        uv run -m metagit.api.main