#!/usr/bin/env python
"""HTTP client tests against the mock EverRoom Gateway."""

from __future__ import annotations

import pytest

from metagit.core.integrations.everroom.client import EverRoomHttpClient, markdown_to_tiptap
from metagit.core.integrations.everroom.errors import (
    EverRoomAuthError,
    EverRoomInvalidResponseError,
    EverRoomNotFoundError,
    EverRoomUnavailableError,
)
from tests.core.integrations.everroom.mock_gateway import (
    ROOM_ID,
    SECRET_TOKEN,
    MockGatewayState,
    start_mock_gateway,
)


def test_health_success() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN)
        health = client.health()
        assert health.status == "ok"
        assert health.service == "nxcore-gateway"
    finally:
        gateway.stop()


def test_authentication_failure_does_not_echo_token() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token="wrong-token")
        with pytest.raises(EverRoomAuthError) as exc:
            client.resolve_room(ROOM_ID)
        assert SECRET_TOKEN not in str(exc.value)
        assert "METAGIT_EVERROOM_TOKEN" in exc.value.message
    finally:
        gateway.stop()


def test_missing_token_fails_before_request() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token="")
        with pytest.raises(EverRoomAuthError) as exc:
            client.resolve_room(ROOM_ID)
        assert "METAGIT_EVERROOM_TOKEN" in exc.value.message
    finally:
        gateway.stop()


def test_room_lookup_success() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN)
        room = client.resolve_room(ROOM_ID)
        assert room.id == ROOM_ID
        assert room.title == "terraform-hcp-migration"
        sources = client.list_room_sources(ROOM_ID)
        documents = client.list_room_documents(ROOM_ID)
        decisions = client.list_room_decisions(ROOM_ID, limit=10)
        context = client.get_room_context(ROOM_ID)
        assert len(sources) == 4
        assert len(documents) == 2
        assert len(decisions) == 3
        assert len(context.next_steps) == 2
    finally:
        gateway.stop()


def test_room_not_found() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN)
        with pytest.raises(EverRoomNotFoundError):
            client.resolve_room("room_missing")
    finally:
        gateway.stop()


def test_malformed_response() -> None:
    gateway = start_mock_gateway(state=MockGatewayState(fail_mode="malformed"))
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN)
        with pytest.raises(EverRoomInvalidResponseError):
            client.resolve_room(ROOM_ID)
    finally:
        gateway.stop()


def test_timeout() -> None:
    gateway = start_mock_gateway(state=MockGatewayState(sleep_seconds=0.4))
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN, timeout_seconds=0.05)
        with pytest.raises(EverRoomUnavailableError) as exc:
            client.health()
        assert exc.value.status == "UNAVAILABLE"
        assert SECRET_TOKEN not in str(exc.value)
    finally:
        gateway.stop()


def test_connection_refused() -> None:
    client = EverRoomHttpClient(endpoint="http://127.0.0.1:1", token=SECRET_TOKEN, timeout_seconds=0.2)
    with pytest.raises(EverRoomUnavailableError) as exc:
        client.health()
    assert exc.value.status == "UNAVAILABLE"
    # Windows may surface this as a timeout rather than an immediate refuse.
    assert "unavailable" in exc.value.message.lower() or "timed out" in exc.value.message.lower()
    assert SECRET_TOKEN not in str(exc.value)


def test_missing_endpoint() -> None:
    with pytest.raises(EverRoomUnavailableError):
        EverRoomHttpClient(endpoint="", token=SECRET_TOKEN)


def test_invalid_endpoint() -> None:
    with pytest.raises(EverRoomUnavailableError):
        EverRoomHttpClient(endpoint="not-a-url", token=SECRET_TOKEN)


def test_upsert_generated_document_imports_then_updates() -> None:
    gateway = start_mock_gateway()
    try:
        client = EverRoomHttpClient(endpoint=gateway.url, token=SECRET_TOKEN)
        created = client.upsert_generated_document(
            room_id=ROOM_ID,
            document_id="metagit-campaign-demo",
            title="Campaign Context (generated by MetaGit)",
            markdown="# Campaign Context\n\nGenerated by MetaGit\n",
        )
        assert created.id == "metagit-campaign-demo"
        updated = client.upsert_generated_document(
            room_id=ROOM_ID,
            document_id="metagit-campaign-demo",
            title="Campaign Context (generated by MetaGit)",
            markdown="# Campaign Context\n\nUpdated\n",
        )
        assert updated.version >= 1
    finally:
        gateway.stop()


def test_markdown_to_tiptap_headings() -> None:
    doc = markdown_to_tiptap("# Title\n\nA paragraph")
    assert doc["type"] == "doc"
    assert doc["content"][0]["type"] == "heading"
    assert SECRET_TOKEN not in str(doc)
