#!/usr/bin/env python
"""Campaign EverRoom attach/detach/create/sync lifecycle tests."""

from __future__ import annotations

from pathlib import Path

import pytest

from metagit.core.campaign.context import CampaignContextService, generated_document_markdown
from metagit.core.campaign.everroom_service import CampaignEverRoomService, EverRoomSettings
from metagit.core.campaign.models import CampaignContextProviderConfig
from metagit.core.campaign.service import CampaignService
from metagit.core.config.models import MetagitConfig
from metagit.core.integrations.everroom.errors import EverRoomNotFoundError, EverRoomUnavailableError
from metagit.core.project.models import ProjectPath
from metagit.core.workspace.models import Workspace, WorkspaceProject
from tests.core.integrations.everroom.fakes import FakeEverRoomClient
from tests.core.integrations.everroom.mock_gateway import ROOM_ID, SECRET_TOKEN


def _config() -> MetagitConfig:
    return MetagitConfig(
        name="ws",
        workspace=Workspace(
            projects=[
                WorkspaceProject(
                    name="demo",
                    repos=[ProjectPath(name="alpha", url="https://github.com/org/alpha.git")],
                ),
            ],
        ),
    )


def _stack(tmp_path: Path, client: FakeEverRoomClient) -> tuple[CampaignService, CampaignEverRoomService]:
    config = _config()
    campaigns = CampaignService(config=config, definition_root=tmp_path)
    campaigns.create(slug="migrate", title="Migrate", repos=["demo/alpha"], goal="Move off HCP")
    context = CampaignContextService(
        campaign_service=campaigns,
        config=config,
        workspace_root=tmp_path,
        definition_root=tmp_path,
        token=SECRET_TOKEN,
        client=client,
    )
    service = CampaignEverRoomService(
        campaign_service=campaigns,
        context_service=context,
        settings=EverRoomSettings(endpoint="http://127.0.0.1:3210", token=SECRET_TOKEN),
        client=client,
    )
    return campaigns, service


def test_attach_persists_room_id_without_token(tmp_path: Path) -> None:
    client = FakeEverRoomClient()
    campaigns, service = _stack(tmp_path, client)
    result = service.attach("migrate", room_id=ROOM_ID, endpoint="http://127.0.0.1:3210")
    assert result.room_id == ROOM_ID
    loaded = campaigns.load("migrate")
    assert loaded is not None
    provider = loaded.everroom_provider()
    assert provider is not None
    assert provider.room_id == ROOM_ID
    yaml_text = (tmp_path / "_campaigns" / "migrate.yml").read_text(encoding="utf-8")
    assert SECRET_TOKEN not in yaml_text
    assert "token" not in yaml_text
    health = service.status("migrate")
    assert health.status == "AVAILABLE"


def test_detach_removes_association_only(tmp_path: Path) -> None:
    client = FakeEverRoomClient()
    campaigns, service = _stack(tmp_path, client)
    service.attach("migrate", room_id=ROOM_ID)
    service.detach("migrate")
    loaded = campaigns.load("migrate")
    assert loaded is not None
    assert loaded.everroom_provider() is None
    assert client.created == []
    health = service.status("migrate")
    assert health.status == "NOT_CONFIGURED"


def test_create_room_projects_campaign_metadata(tmp_path: Path) -> None:
    client = FakeEverRoomClient()
    _, service = _stack(tmp_path, client)
    result = service.create_room("migrate")
    assert result.room_id.startswith("room-created-")
    assert client.created[0].title == "Migrate"
    assert "Move off HCP" in (client.created[0].summary or "")
    assert SECRET_TOKEN not in (client.created[0].summary or "")


def test_sync_writes_generated_document(tmp_path: Path) -> None:
    client = FakeEverRoomClient()
    _, service = _stack(tmp_path, client)
    service.attach("migrate", room_id=ROOM_ID)
    result = service.sync("migrate")
    assert result.generated is True
    assert result.document_id.startswith("metagit-campaign-")
    assert client.upserts
    markdown = client.upserts[0]["markdown"]
    assert "Generated by MetaGit" in markdown
    assert SECRET_TOKEN not in markdown
    assert "migrate" in markdown


def test_sync_fails_when_unavailable(tmp_path: Path) -> None:
    client = FakeEverRoomClient(error=EverRoomUnavailableError("EverRoom Gateway is unavailable"))
    campaigns, service = _stack(tmp_path, client)
    campaigns.upsert_context_provider(
        "migrate",
        CampaignContextProviderConfig(type="everroom", room_id=ROOM_ID, endpoint="http://127.0.0.1:3210"),
    )
    with pytest.raises(EverRoomUnavailableError):
        service.sync("migrate")


def test_stale_room_reference_on_attach(tmp_path: Path) -> None:
    client = FakeEverRoomClient()
    _, service = _stack(tmp_path, client)
    with pytest.raises(EverRoomNotFoundError):
        service.attach("migrate", room_id="room_stale")
    yaml_text = (tmp_path / "_campaigns" / "migrate.yml").read_text(encoding="utf-8")
    assert "room_stale" not in yaml_text


def test_generated_markdown_omits_credentials() -> None:
    from metagit.core.campaign.context_models import (
        CampaignContextResult,
        CampaignEnvelope,
        EverRoomContextSlice,
        MetagitTechnicalContext,
    )

    packet = CampaignContextResult(
        campaign=CampaignEnvelope(id="c1", title="C1", objective="obj", status="active"),
        metagit=MetagitTechnicalContext(),
        everroom=EverRoomContextSlice(status="NOT_CONFIGURED"),
    )
    text = generated_document_markdown(packet)
    assert SECRET_TOKEN not in text
    assert "Authorization" not in text
