tenant_config:
  tenant_id: "tenant-a"
  tenant_name: "Acme Corporation"
  tenant_description: "Acme Corporation's development team configuration"
  
  # Provider configuration for this tenant
  providers:
    github:
      enabled: true
      api_token: "${GITHUB_TOKEN_ACME}"
      base_url: "https://api.github.com"
    gitlab:
      enabled: false
      api_token: ""
      base_url: "https://gitlab.com/api/v4"
  
  # LLM configuration for this tenant
  llm:
    enabled: true
    provider: "openrouter"
    provider_model: "gpt-4o-mini"
    embedder: "ollama"
    embedder_model: "nomic-embed-text"
    api_key: "${OPENROUTER_API_KEY_ACME}"

  # Detection settings for this tenant
  tenant_max_concurrent_jobs: 10
  tenant_detection_timeout: 600

  # Custom settings for this tenant
  tenant_settings:
    organization_name: "Acme Corporation"
    team_id: "dev-team-1"
    notification_email: "dev-team@acme.com"
    auto_scan_enabled: true
    scan_frequency: "daily"
  # Metadata
  tenant_created_at: "2024-01-15T10:00:00Z"
  tenant_updated_at: "2024-01-15T10:00:00Z"
  tenant_is_active: true 