config:
  version: "1.0.0"
  description: "Metagit configuration with multi-tenancy enabled"
  
  # Tenant configuration
  tenant:
    enabled: true
    default_tenant: "default"
    tenant_header: "X-Tenant-ID"
    tenant_required: true
    allowed_tenants:
      - "tenant-a"
      - "tenant-b"
      - "tenant-c"
      - "default"
  
  # LLM configuration
  llm:
    enabled: false
    provider: "openrouter"
    provider_model: "gpt-4o-mini"
    embedder: "ollama"
    embedder_model: "nomic-embed-text"
    api_key: ""
  
  # Workspace configuration
  workspace:
    path: "./.metagit"
    default_project: "default"
  
  # Profiles configuration
  profiles:
    profile_config_path: "~/.config/metagit/profiles"
    default_profile: "default"
    boundaries: []
  
  # Provider configuration
  providers:
    github:
      enabled: false
      api_token: ""
      base_url: "https://api.github.com"
    gitlab:
      enabled: false
      api_token: ""
      base_url: "https://gitlab.com/api/v4"
  
  # Other settings
  editor: "code"
  api_url: ""
  api_version: ""
  api_key: ""
  cicd_file_data: ""
  file_type_data: ""
  package_manager_data: ""
  default_project: "" 