#!/usr/bin/env python
"""
Generate a documented YAML exemplar for MetagitConfig with field descriptions as comments.
"""

from __future__ import annotations

import enum
import types
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Union, get_args, get_origin

import yaml
from pydantic import BaseModel
from pydantic.fields import FieldInfo

from metagit import DATA_PATH
from metagit.core.config.models import MetagitConfig
from metagit.core.utils.yaml_class import yaml as metagit_yaml


def load_example_overrides() -> dict[str, Any]:
    """Load optional nested overrides for the generated exemplar."""
    override_path = Path(DATA_PATH) / "config-example-overrides.yml"
    if not override_path.is_file():
        return {}
    with override_path.open("r", encoding="utf-8") as handle:
        loaded = metagit_yaml.safe_load(handle)
    return loaded if isinstance(loaded, dict) else {}


def deep_merge(base: dict[str, Any], overrides: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge overrides into base (overrides win)."""
    merged = dict(base)
    for key, value in overrides.items():
        if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


class ConfigExampleGenerator:
    """Build a representative MetagitConfig-shaped dict for documentation."""

    def __init__(self, overrides: dict[str, Any] | None = None) -> None:
        self._overrides = overrides or {}

    def build(self, *, include_workspace: bool = True) -> dict[str, Any]:
        """Return a nested dict suitable for YAML serialization."""
        payload = self._sample_model(MetagitConfig)
        if not include_workspace:
            payload.pop("workspace", None)
        return deep_merge(payload, self._overrides)

    def render_yaml(
        self,
        *,
        include_workspace: bool = True,
        comment_style: str = "line",
    ) -> str:
        """Render YAML with per-field description comments."""
        payload = self.build(include_workspace=include_workspace)
        header = (
            "# NON-PRODUCTION EXEMPLAR — generated by `metagit config example`.\n"
            "# Field descriptions come from Pydantic models; edit before use.\n"
        )
        if comment_style != "line":
            return header + yaml.dump(
                payload,
                default_flow_style=False,
                sort_keys=False,
                allow_unicode=True,
            )
        lines = header.splitlines(keepends=True)
        lines.append("\n")
        lines.extend(
            self._render_mapping(
                payload,
                MetagitConfig,
                indent=0,
            )
        )
        return "".join(lines)

    def _render_mapping(
        self,
        data: dict[str, Any],
        model: type[BaseModel],
        *,
        indent: int,
    ) -> list[str]:
        """Render one mapping using model field order and descriptions."""
        pad = "  " * indent
        lines: list[str] = []
        fields = model.model_fields
        for key, value in data.items():
            if key not in fields:
                lines.extend(self._render_key_value(key, value, indent=indent))
                continue
            field_info = fields[key]
            description = field_info.description
            if description:
                for desc_line in str(description).splitlines():
                    lines.append(f"{pad}# {desc_line}\n")
            annotation = field_info.annotation
            nested_model = self._nested_model_for_annotation(annotation)
            if isinstance(value, dict) and nested_model is not None:
                lines.append(f"{pad}{key}:\n")
                lines.extend(self._render_mapping(value, nested_model, indent=indent + 1))
            elif isinstance(value, list) and value and nested_model is not None:
                lines.append(f"{pad}{key}:\n")
                for item in value:
                    if isinstance(item, dict):
                        lines.append(f"{pad}  -\n")
                        lines.extend(self._render_mapping(item, nested_model, indent=indent + 2))
                    else:
                        lines.append(f"{pad}  - {self._format_scalar(item)}\n")
            else:
                lines.extend(self._render_key_value(key, value, indent=indent))
        return lines

    def _render_key_value(self, key: str, value: Any, *, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(value, dict):
            lines = [f"{pad}{key}:\n"]
            for sub_key, sub_value in value.items():
                lines.extend(self._render_key_value(sub_key, sub_value, indent=indent + 1))
            return lines
        if isinstance(value, list):
            lines = [f"{pad}{key}:\n"]
            for item in value:
                if isinstance(item, (dict, list)):
                    lines.append(f"{pad}  - {yaml.dump(item, default_flow_style=True).strip()}\n")
                else:
                    lines.append(f"{pad}  - {self._format_scalar(item)}\n")
            return lines
        return [f"{pad}{key}: {self._format_scalar(value)}\n"]

    def _format_scalar(self, value: Any) -> str:
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        if isinstance(value, datetime):
            return value.isoformat()
        escaped = str(value).replace("\n", "\\n")
        if any(ch in escaped for ch in ":{}[]&*#?|-<>=!%@") or escaped.startswith(" ") or not escaped:
            return yaml.dump(escaped, default_flow_style=True).strip()
        return escaped

    def _sample_model(self, model: type[BaseModel]) -> dict[str, Any]:
        payload: dict[str, Any] = {}
        for name, field_info in model.model_fields.items():
            payload[name] = self._sample_field(name, field_info, model)
        return payload

    def _sample_field(
        self,
        name: str,
        field_info: FieldInfo,
        model: type[BaseModel],
    ) -> Any:
        _ = model
        if field_info.default_factory is not None and name in {
            "artifacts",
            "paths",
            "dependencies",
        }:
            inner = self._sample_annotation(field_info.annotation, name)
            return [inner] if isinstance(inner, dict) else inner
        if field_info.default_factory is not None and name == "sources":
            return []
        annotation = field_info.annotation
        return self._sample_annotation(annotation, name)

    def _sample_annotation(self, annotation: Any, field_name: str) -> Any:
        origin = get_origin(annotation)
        if origin is Union or isinstance(annotation, types.UnionType):
            args = [arg for arg in get_args(annotation) if arg is not type(None)]
            if not args:
                return None
            return self._sample_annotation(args[0], field_name)

        if origin is list:
            inner_args = get_args(annotation)
            inner = inner_args[0] if inner_args else Any
            sampled = self._sample_annotation(inner, field_name)
            return [sampled] if sampled is not None else []

        nested = self._nested_model_for_annotation(annotation)
        if nested is not None:
            return self._sample_model(nested)

        if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
            return next(iter(annotation)).value

        if annotation is bool:
            return False
        if annotation is int:
            return 0
        if annotation is float:
            return 0.0
        if annotation is str:
            return self._scalar_for_name(field_name)

        return self._scalar_for_name(field_name)

    def _nested_model_for_annotation(
        self,
        annotation: Any,
    ) -> type[BaseModel] | None:
        origin = get_origin(annotation)
        if origin is Union or isinstance(annotation, types.UnionType):
            for arg in get_args(annotation):
                nested = self._nested_model_for_annotation(arg)
                if nested is not None:
                    return nested
            return None
        if origin is list:
            args = get_args(annotation)
            if args:
                return self._nested_model_for_annotation(args[0])
            return None
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            return annotation
        return None

    def _scalar_for_name(self, field_name: str) -> Any:
        lowered = field_name.lower()
        if lowered in {"email"}:
            return "maintainer@example.com"
        if lowered in {"url", "forked_from"}:
            return "https://example.com/org/repo"
        if lowered.endswith("_at") or lowered in {"created_at", "last_commit_at"}:
            return datetime(2026, 1, 1, tzinfo=timezone.utc).isoformat()
        if lowered in {"name"}:
            return "example-name"
        if lowered in {"description", "agent_instructions", "agent_prompt"}:
            return "Example text for documentation; replace before production use."
        if lowered in {"ref", "pattern", "definition", "file", "location", "role"}:
            return "example"
        if lowered in {"language_version"}:
            return "3.12"
        if lowered in {"language"}:
            return "python"
        if lowered in {"package_manager"}:
            return "uv"
        if lowered in {"tags"}:
            return {"example": "documentation"}
        if lowered in {"metadata"}:
            return {"source": "metagit-config-example"}
        if lowered in {"sync"}:
            return True
        if lowered in {"protected", "archived", "template", "has_ci", "has_tests"}:
            return False
        if lowered in {"enabled"}:
            return False
        if lowered in {
            "stars",
            "forks",
            "open_issues",
            "contributors",
            "open",
            "merged_last_30d",
        }:
            return 0
        return "example-value"
