name: Pull Request and Push Action

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed]
  push:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  secret-scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # call-test:
  #   uses: ./.github/workflows/test-lint.yml
  #   permissions:
  #     contents: read
  #   with:
  #     ref: ${{ github.event.pull_request.head.sha }}
  call-lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml
    permissions:
      contents: read
    with:
      ref: ${{ github.event.pull_request.head.sha }}